version: 0.2

env:
  variables:
    REPOSITORY_URI: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/posts'
    SERVICE_NAME: posts

phases:
  install:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $SERVICE_NAME -f post/Dockerfile .
      - docker tag $SERVICE_NAME:latest $REPOSITORY_URI:latest

  post_build:
    commands:
      - echo Pushing the Docker image to Amazon ECR...
      - docker push $REPOSITORY_URI:latest

artifacts:
  files: '**/*'
  discard-paths: yes
  base-directory: .


